---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator/

commonLabels:
  app.kubernetes.io/name: imagepullsecret-patcher

images:
  - name: imagepullsecret-patcher
    newName: quay.io/titansoft/imagepullsecret-patcher
    newTag: "v0.14"

...
