---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator/

images:
  - name: imagepullsecret-patcher
    newName: quay.io/titansoft/imagepullsecret-patcher
    newTag: "v0.14"

...
