---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: imagepullsecret-patcher

rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
      - "serviceaccounts"
    verbs:
      - "list"
      - "patch"
      - "create"
      - "get"
      - "delete"
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - "list"
      - "get"

...
