---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yml
  - clusterrole.yml
  - clusterrolebinding.yml
  - deployment.yml

configMapGenerator:
  - name: imagepullsecret-patcher
    options:
      labels:
        app.kubernetes.io/name: imagepullsecret-patcher
        app.kubernetes.io/component: operator
    literals:
      - CONFIG_FORCE=true
      - CONFIG_ALLSERVICEACCOUNT=true
      - CONFIG_SECRETNAME=imagepullsecret-registry
      - CONFIG_DOCKERCONFIGJSONPATH=/etc/docker/.dockerconfigjson

secretGenerator:
  - name: imagepullsecret-patcher
    options:
      labels:
        app.kubernetes.io/name: imagepullsecret-patcher
        app.kubernetes.io/component: operator
    literals: []

...
