---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yml
  - clusterrole.yml
  - clusterrolebinding.yml
  - deployment.yml

commonLabels:
  app.kubernetes.io/component: operator

configMapGenerator:
  - name: imagepullsecret-patcher
    literals:
      - CONFIG_FORCE=true
      - CONFIG_ALLSERVICEACCOUNT=true
      - CONFIG_SECRETNAME=imagepullsecret-registry
      - CONFIG_DOCKERCONFIGJSONPATH=/etc/docker/.dockerconfigjson

...
